site:
  about:
    siteName: 'FBME'
    subtitle: 'Function Blocks Modelling Environment'
  theme: 'Editorial'
  baseUrl: 'https://jetbrains.github.io/fbme'

theme:
  social:
    github: 'JetBrains/fbme'
  primaryColor: '#00bfff'
  menu:
    - type: 'separator'
      title: 'User Manuals'
    - type: 'wiki'
      section: 'userManual'
    - type: 'separator'
      title: 'Developer Guides'
    - type: 'wiki'
      section: 'devGuides'
    - type: 'sourcedocPages'
      moduleType: 'javadoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'API Documentation'
  extraCss:
    - 'assets/css/custom.scss'

wiki:
  sections:
    - 'userManual'
    - 'devGuides'

javadoc:
  homePagePermalink:   'docs'
  sourcePagePermalink: 'docs/:sourceDocPath'
  sourceDirs:
    - '../../../../library/src/main/java'

services:
  publications:
    stages:
      - type: githubPages
        branch: gh-pages
        username: qradimir
        repo: 'JetBrains/fbme'